# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Magnum Pan Africa
description: > # this means to ignore newlines until "baseurl:"
  Magnum is the newest Pan African digital business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://magnumpanafrica.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [
  .git,
  .gitignore,
  .sass-cache,
  package.json,
  gulpfile.js,
  node_modules,
  '**/*.log'
]

# Site environment overrode in _config.dev.yml
env: production
